// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projeto_Backend_IQuirium.Repository;

#nullable disable

namespace Projeto_Backend_IQuirium.Migrations
{
    [DbContext(typeof(ProjetoBackendIQuiriumContext))]
    [Migration("20241101034846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Projeto_Backend_IQuirium.Model.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("Criado_em")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("Id_destinatario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_usuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo_feedback")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_destinatario");

                    b.HasIndex("Id_usuario");

                    b.ToTable("feedback1", (string)null);
                });

            modelBuilder.Entity("Projeto_Backend_IQuirium.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Criado_em")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("usuario1", (string)null);
                });

            modelBuilder.Entity("Projeto_Backend_IQuirium.Model.Feedback", b =>
                {
                    b.HasOne("Projeto_Backend_IQuirium.Model.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("Id_destinatario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_Backend_IQuirium.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
